import numpy as np
from numpy.typing import ArrayLike

from .Field import Field
from ..solver import diffract

def fpr1(
    model,
    lmbda: float,
    F0,
    x: ArrayLike | None = None,
    points: int = 250,
):
    """
    Propagate the field through the first free propagation region (FPR1).

    Parameters
    ----------
    model : AWG
        AWG model object.
    lmbda : float
        Wavelength.
    F0 : Field
        Input field.
    x : ArrayLike | None, optional
        Output-plane coordinate vector. If None, auto-generate it.
    points : int, optional
        Number of points for autogenerated coordinates.

    Returns
    -------
    Field
        Propagated and normalized field at the output plane of the first FPR.
    """
    x0 = np.asarray(F0.x).reshape(-1)
    u0 = np.asarray(F0.Ex).reshape(-1)  # same TODO as MATLAB

    ns = model.get_slab_waveguide().index(lmbda, 1)
    ns = float(np.asarray(ns).reshape(-1)[0])

    if x is None:
        s = np.linspace(-0.5, 0.5, points) * (model.N + 4) * model.d
    else:
        s = np.asarray(x).reshape(-1)

    r = model.R / 2
    if model.confocal:
        r = model.R

    # correct input phase curvature
    a = x0 / r
    xp = r * np.tan(a)
    dp = r / np.cos(a) - r
    up = u0 * np.exp(1j * 2 * np.pi / lmbda * ns * dp)  # retard phase

    # cartesian coordinates
    a = s / model.R
    xf = model.R * np.sin(a)
    zf = model.defocus + model.R * np.cos(a)

    # calculate diffraction
    u = diffract(lmbda / ns, up, xp, xf, zf)

    # return normalized field
    return Field(s, u).normalize(F0.power())