import numpy as np
from numpy.typing import ArrayLike

from .Field import Field
from ..solver import diffract


def fpr2(
    model,
    lmbda: float,
    F0,
    x: ArrayLike | None = None,
    points: int = 250,
):
    """
    Propagate the field through the second free propagation region (FPR2).

    Parameters
    ----------
    model : AWG
        AWG model object.
    lmbda : float
        Wavelength.
    F0 : Field
        Input field.
    x : ArrayLike | None, optional
        Output-plane coordinate vector. If None, auto-generate it.
    points : int, optional
        Number of points for autogenerated coordinates.

    Returns
    -------
    Field
        Propagated and normalized field at the output plane of the second FPR.
    """
    x0 = np.asarray(F0.x).reshape(-1)
    u0 = np.asarray(F0.Ex).reshape(-1)  # same TODO as MATLAB

    ns = model.get_slab_waveguide().index(lmbda, 1)
    ns = float(np.asarray(ns).reshape(-1)[0])

    r = model.R / 2
    if model.confocal:
        r = model.R

    if x is None:
        s = np.linspace(-np.pi / 2, np.pi / 2, points) * r
    else:
        s = np.asarray(x).reshape(-1)

    # correct input phase curvature
    a = x0 / model.R
    xp = model.R * np.tan(a)
    dp = model.R / np.cos(a) - model.R
    up = u0 * np.exp(1j * 2 * np.pi / lmbda * ns * dp)  # retarded phase

    # cartesian coordinates
    a = s / r
    xf = r * np.sin(a)
    zf = (model.defocus + model.R - r) + r * np.cos(a)

    # calculate diffraction
    u = diffract(lmbda / ns, up, xp, xf, zf)

    # return normalized field
    F = Field(s, u)
    F.normalize(F0.power())
    return F