from __future__ import annotations
from dataclasses import dataclass, field
import numpy as np
from numpy.typing import ArrayLike

from ..material import Material
from ..solver import rectf, wgindex, gmode, wgmode
from .Field import Field


@dataclass
class Waveguide:
    """
    General-purpose waveguide class.

                 |<   w   >|
                  _________           _____
                 |         |            ^
     ___    _____|         |_____
      ^                                 h
      t
     _v_    _____________________     __v__

    Parameters
    ----------
    clad : Material | float | callable | str
        Top cladding material.
    core : Material | float | callable | str
        Core material.
    subs : Material | float | callable | str
        Substrate material.
    w : float
        Core width.
    h : float
        Core height.
    t : float
        Slab thickness for rib waveguides. Use t == h for a slab waveguide.
    """

    clad: "Material | float | callable | str" = field(default_factory=lambda: Material("SiO2"))
    core: "Material | float | callable | str" = field(default_factory=lambda: Material("Si"))
    subs: "Material | float | callable | str" = field(default_factory=lambda: Material("SiO2"))
    w: float = 0.500
    h: float = 0.200
    t: float = 0.0

    def __post_init__(self) -> None:
        if self.w <= 0:
            raise ValueError("w must be positive.")
        if self.h <= 0:
            raise ValueError("h must be positive.")
        if self.t < 0:
            raise ValueError("t must be nonnegative.")

        self.clad = self._ensure_material(self.clad)
        self.core = self._ensure_material(self.core)
        self.subs = self._ensure_material(self.subs)

    @staticmethod
    def _ensure_material(value) -> "Material":
        if isinstance(value, Material):
            return value
        return Material(value)

    def index(self, lmbda: float, modes: int | float = np.inf) -> np.ndarray:
        """
        Compute effective indices of the guided modes.
        """
        n1 = self.core.index(lmbda)
        n2 = self.clad.index(lmbda)
        n3 = self.subs.index(lmbda)

        neff = wgindex(
            lmbda=lmbda,
            w=self.w,
            h=self.h,
            t=self.t,
            na=n2,
            nc=n1,
            ns=n3,
            modes=modes,
        )
        return neff

    def groupindex(self, lmbda: float, modes: int | float = np.inf) -> np.ndarray:
        """
        Compute group index using a finite-difference approximation.
        """
        n0 = self.index(lmbda, modes)
        n1 = self.index(lmbda + 0.01, modes)
        n2 = self.index(lmbda - 0.01, modes)

        return n0 - lmbda * (n1 - n2) / 0.02

    def mode(
        self,
        lmbda: float,
        x: ArrayLike | None = None,
        mode_type: str = "gaussian",
        xlimits: tuple[float, float] | None = None,
        points: int = 100,
    ) -> "Field":
        """
        Build a waveguide mode field.

        Parameters
        ----------
        lmbda : float
            Wavelength.
        x : ArrayLike | None
            Coordinate vector. If None, generated from xlimits and points.
        mode_type : str
            One of {'rect', 'gaussian', 'solve'}.
        xlimits : tuple[float, float] | None
            Range for autogenerated x. Default is (-3*w, 3*w).
        points : int
            Number of coordinate points if x is autogenerated.

        Returns
        -------
        Field
            Field object containing x, E, H.
        """
        n1 = self.core.index(lmbda)
        n2 = self.clad.index(lmbda)
        n3 = self.subs.index(lmbda)

        if xlimits is None:
            xlimits = (-3 * self.w, 3 * self.w)

        if x is None:
            x = np.linspace(xlimits[0], xlimits[1], points)
        else:
            x = np.asarray(x).reshape(-1)

        mode_type = mode_type.lower()

        if mode_type == "rect":
            n = (n1 + n2) / 2
            n0 = 120 * np.pi

            amp = 1 / (self.w ** 0.25)
            rect = rectf(x / self.w)

            E = [amp * rect, np.zeros_like(x, dtype=complex), np.zeros_like(x, dtype=complex)]
            H = [
                np.zeros_like(x, dtype=complex),
                n / n0 * amp * rect,
                np.zeros_like(x, dtype=complex),
            ]

        elif mode_type == "gaussian":
            E, H, _ = gmode(
                lmbda=lmbda,
                W=self.w,
                H=self.h,
                nclad=n2,
                ncore=n1,
                x=x,
            )

        elif mode_type == "solve":
            E, H, _, _ = wgmode(
                lmbda=lmbda,
                w=self.w,
                h=self.h,
                t=self.t,
                na=n2,
                nc=n1,
                ns=n3,
                x=x,
            )

        else:
            raise ValueError("Unknown mode type.")

        return Field(x, E, H)